language: ruby
rvm:
  - 2.4.1

addons:
  ssh_known_hosts:
  - in.pycon.org

script:
- bundle exec jekyll build

cache: bundler

branches:
  only:
  - master

deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: _site
  on:
    branch: master

after_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key root@in.pycon.org provision

before_install:
- openssl aes-256-cbc -K $encrypted_b3f2875e8943_key -iv $encrypted_b3f2875e8943_iv
  -in deploy_key.enc -out ./deploy_key -d
